theme: jekyll-theme-minimal
title: marcusg.se
description: repeat { think twice; code once }
#logo: [Location of the logo]
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-gist
  - jekyll-assets

jekyll_get:
  data: gistlist
  json: 'https://api.github.com/users/marggeld/gists'
  cache: false


